3 new functions added to `y_weapondata`
pawn-lang/YSI-Includes pull request #609
Opened 2022-08-29 10:51 UTC by DEntis-T

2022-08-29 11:12 UTC, DEntis-T commented
OK, it's probably ready to be merged now, unless someone suggests something new on Discord

2022-09-02 10:52 UTC, Y-Less requested changes

2022-09-02 10:52 UTC, Y-Less commented on YSI_Game/y_weapondata/y_weapondata_entry.inc
>  Contributors:
Why has this part changed?

2022-09-02 10:52 UTC, Y-Less commented on YSI_Game/y_weapondata/y_weapondata_entry.inc
> -
All these mising blank lines in the header.

2022-09-02 10:52 UTC, Y-Less commented on YSI_Game/y_weapondata/y_weapondata_entry.inc
> +#define WEAPON_TYPE_UNKNOWN				WeaponType:0
Usea an enum.

2022-09-02 10:52 UTC, Y-Less commented on YSI_Game/y_weapondata/y_weapondata_entry.inc
> +#define WEAPON_TYPE_RIFLE 				WeaponType:6
Should the type numbers not match the slot numbers?  Or if not ohw are they different (please document the difference)?

2022-09-02 10:52 UTC, Y-Less commented on YSI_Game/y_weapondata/y_weapondata_entry.inc
> +#define WEAPON_TYPE_USEABLE				WeaponType:9
`USEABLE` is a terrible name, I know what you mean but all weapons are "useable".  Maybe `EQUIPMENT`?

2022-09-02 10:52 UTC, Y-Less commented on YSI_Game/y_weapondata/y_weapondata_entry.inc
> +#define WEAPON_TYPE_PROJECTILE 			WeaponType:7
`ARTILLERY`

2022-09-02 19:58 UTC, DEntis-T commented
@Y-Less Solved the things you've posted, but something doesn't seem to work at a glance.
This code was working fine:
```pawn
new weapid = 33;
    new WeaponType:type = Weapon_GetType(weapid);
    printf("Weapon type of weapon %i is %i", weapid, _:type);
    if(type == WEAPON_TYPE_LONG_RIFLE)
    {
        printf("weapon type is WEAPON_TYPE_LONG_RIFLE");
    }
```
But suddenly it started to give a runtime error with an ID of 6 saying "Invalid instruction". I don't see anything invalid here

2022-09-02 20:00 UTC, DEntis-T commented
> @Y-Less Solved the things you've posted, but something doesn't seem to work at a glance. This code was working fine:
> 
> ```pawn
> new weapid = 33;
>     new WeaponType:type = Weapon_GetType(weapid);
>     printf("Weapon type of weapon %i is %i", weapid, _:type);
>     if(type == WEAPON_TYPE_LONG_RIFLE)
>     {
>         printf("weapon type is WEAPON_TYPE_LONG_RIFLE");
>     }
> ```
> 
> But suddenly it started to give a runtime error with an ID of 6 saying "Invalid instruction". I don't see anything invalid here

Maybe the problem is in this part:
```pawn
    if(type == WEAPON_TYPE_LONG_RIFLE)
    {
        printf("weapon type is WEAPON_TYPE_LONG_RIFLE");
    }
```
I'm currently really tired so I will leave this as it is now

2022-09-03 08:50 UTC, DEntis-T commented
Nevermind, I'll get it fixed

2022-09-28 05:51 UTC, DEntis-T commented
@Y-Less It works now.

2022-09-28 12:28 UTC, closed without merging